# ob_atom.OBAtom { #clerq.ob_atom.OBAtom }

```python
ob_atom.OBAtom(
    label=None,
    num_states=1,
    energies=None,
    decays=None,
    initial_state=None,
    fields=None,
)
```



## Methods

| Name | Description |
| --- | --- |
| [add_field](#clerq.ob_atom.OBAtom.add_field) | Add a Field to the list given a dict representing the field. |
| [build_fields](#clerq.ob_atom.OBAtom.build_fields) | Build the field list given a list of dicts representing fields. |
| [build_initial_state](#clerq.ob_atom.OBAtom.build_initial_state) | Build the initial density matrix for the atom. |
| [build_operators](#clerq.ob_atom.OBAtom.build_operators) | Build the quantum operators representing the bare Hamiltonian, |
| [get_detunings](#clerq.ob_atom.OBAtom.get_detunings) | Returns a list of detunings, one for each field in fields. |
| [get_fields_sum_coherence](#clerq.ob_atom.OBAtom.get_fields_sum_coherence) | Returns the sum coherences of the atom density matrix for each |
| [set_H_Delta](#clerq.ob_atom.OBAtom.set_H_Delta) | Set the detuning part of the interaction Hamiltonian, H_Delta, |
| [set_H_Omega](#clerq.ob_atom.OBAtom.set_H_Omega) |  |
| [to_json_str](#clerq.ob_atom.OBAtom.to_json_str) | Return a JSON string representation of the Atom object. |

### add_field { #clerq.ob_atom.OBAtom.add_field }

```python
ob_atom.OBAtom.add_field(field_dict)
```

Add a Field to the list given a dict representing the field.

### build_fields { #clerq.ob_atom.OBAtom.build_fields }

```python
ob_atom.OBAtom.build_fields(field_dicts)
```

Build the field list given a list of dicts representing fields.

### build_initial_state { #clerq.ob_atom.OBAtom.build_initial_state }

```python
ob_atom.OBAtom.build_initial_state(initial_state=None)
```

Build the initial density matrix for the atom.

The default is for all of the population to be in ``|0><0|``.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                                        | Default    |
|--------|--------|----------------------------------------------------|------------|
| rho0   |        | a list or array of populations, length num_states. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type    | Description                                        |
|--------|---------|----------------------------------------------------|
|        | qu.Qobj | Qu.Qobj: A density matrix representing the initial |

#### Notes {.doc-section .doc-section-notes}

- The elements must sum to 1 (as this will be the trace of the
    density matrix).

### build_operators { #clerq.ob_atom.OBAtom.build_operators }

```python
ob_atom.OBAtom.build_operators()
```

Build the quantum operators representing the bare Hamiltonian,
collapse operators and interaction Hamiltonian.

### get_detunings { #clerq.ob_atom.OBAtom.get_detunings }

```python
ob_atom.OBAtom.get_detunings()
```

Returns a list of detunings, one for each field in fields.

### get_fields_sum_coherence { #clerq.ob_atom.OBAtom.get_fields_sum_coherence }

```python
ob_atom.OBAtom.get_fields_sum_coherence(states_t=None)
```

Returns the sum coherences of the atom density matrix for each
    field, including the relative strength factors.

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type               | Description                                                        | Default   |
|----------|--------------------|--------------------------------------------------------------------|-----------|
| states_t | np.ndarray \| None | (optional) a states_t object. If not provided, use self.states_t() | `None`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                                 |
|--------|------------|---------------------------------------------|
|        | np.ndarray | np.ndarray of shape (num_fields, t_steps+1) |

### set_H_Delta { #clerq.ob_atom.OBAtom.set_H_Delta }

```python
ob_atom.OBAtom.set_H_Delta(detunings)
```

Set the detuning part of the interaction Hamiltonian, H_Delta,
    given a list of detunings.

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type          | Description                                         | Default    |
|-----------|---------------|-----------------------------------------------------|------------|
| detunings | list\[float\] | list of floats: detunings of each field in the list | _required_ |

### set_H_Omega { #clerq.ob_atom.OBAtom.set_H_Omega }

```python
ob_atom.OBAtom.set_H_Omega(rabi_freqs, rabi_freq_t_funcs, rabi_freq_t_args)
```

#### Parameters {.doc-section .doc-section-parameters}

| Name              | Type          | Description   | Default    |
|-------------------|---------------|---------------|------------|
| rabi_freqs        | list\[float\] | [floats]      | _required_ |
| rabi_freq_t_funcs | list          | [strings]     | _required_ |
| rabi_freqs_t_args |               | [dicts]       | _required_ |

Returns:

### to_json_str { #clerq.ob_atom.OBAtom.to_json_str }

```python
ob_atom.OBAtom.to_json_str()
```

Return a JSON string representation of the Atom object.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                      |
|--------|--------|--------------------------------------------------|
|        | str    | (string) JSON representation of the Atom object. |